AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  patient-checkout

  Sample SAM Template for patient-checkout

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
    MemorySize: 512
    Runtime: java11
Resources:
  PatientCheckoutBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}-${AWS::AccountId}-${AWS::Region}
  PatientCheckoutTopic:
    Type: AWS::SNS::Topic
  PatientCheckoutFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: PatientCheckoutLambda
      Handler: net.ontopsolutions.lambda.s3sns.PatientCheckOutLambda::handle
      Architectures:
        - x86_64
      Policies:
        - S3ReadPolicy:
            BucketName: !Sub ${AWS::StackName}-${AWS::AccountId}-${AWS::Region}
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt PatientCheckoutTopic.TopicName
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PATIENT_CHECKOUT_TOPIC: !Ref PatientCheckoutTopic
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1 # More info about tiered compilation https://aws.amazon.com/blogs/compute/optimizing-aws-lambda-function-performance-for-java/
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref PatientCheckoutBucket
            Events: S3:ObjectCreated:*
  BillManagementFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: PatientCheckoutLambda
      Handler: net.ontopsolutions.lambda.s3sns.BillManagementLambda::handle
      Architectures:
        - x86_64
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1 # More info about tiered compilation https://aws.amazon.com/blogs/compute/optimizing-aws-lambda-function-performance-for-java/
      Events:
        SNSEvent:
          Type: SNS
          Properties:
            Topic: !Ref PatientCheckoutTopic
